# each service is a container instance
services:
  # each container has a name which can be referenced in other containers
  mariadb:

    build: ./requirements/mariadb # where to find the Dockerfile to build the image
    container_name: inception-mariadb # name of the container
    image: mariadb-image # how the image will be tagged if it hasnt been built yet
    restart: 'no' # ensures automatic restart of container in case it crashes
    environment: #pulls values from .env file (needs to be in same folder as docker-compose.yml)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: inception-nginx
    image: nginx-image
    restart: 'no'
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    # make sure the volume path exists and has the right permissions on the host machine (user www-data)
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception-network

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: inception-wordpress
    image: wordpress-image
    restart: 'no'
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    # ports:
    #   - "9000:9000"
    # make sure the volume path exists and has the right permissions on the host machine (user www-data)
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception-network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chimpansky/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chimpansky/data/wordpress
      o: bind

networks:
  inception-network:
    driver: bridge