# each service is a container instance
services:
  # each container has a name which can be referenced in other containers
  mariadb:

    build: ./requirements/mariadb # where to find the Dockerfile to build the image
    container_name: inception-mariadb # name of the container
    image: mariadb-image # how the image will be tagged if it hasnt been built yet
    restart: always # ensures automatic restart of container in case it crashes
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - .env

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: inception-nginx
    image: nginx-image
    restart: always
    # make sure the volume path exists and has the right permissions on the host machine (user www-data)
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    container_name: inception-wordpress
    image: wordpress-image
    restart: always
    # make sure the volume path exists and has the right permissions on the host machine (user www-data)
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    env_file:
      - .env

  redis:
    build: ./requirements/bonus/redis
    container_name: inception-redis
    image: redis-image
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    container_name: inception-adminer
    image: adminer-image
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception-network
    env_file:
      - .env

  website:
    build: ./requirements/bonus/website
    container_name: inception-website
    image: website-image
    restart: always
    ports:
      - "90:90"
    networks:
      - inception-network
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

networks:
  inception-network:
    driver: bridge