# each service is a container instance
services:
  # each container has a name which can be referenced in other containers
  mariadb:
    build: ./requirements/mariadb # where to find the Dockerfile to build the image
    container_name: inception-mariadb # name of the container
    image: mariadb:v1 # how the image will be tagged if it hasnt been built yet
    restart: always # ensures automatic restart of container in case it crashes
    volumes:  # which volume to mount to the container (see volumes section below)
      - mariadb_data:/var/lib/mysql
    networks: # which network to connect to
      - inception-network
    env_file: # which environment file to use
      - .env

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: inception-nginx
    image: nginx:v1
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    container_name: inception-wordpress
    image: wordpress:v1
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    env_file:
      - .env

# bonus services:
  redis:
    build: ./requirements/bonus/redis
    container_name: inception-redis
    image: redis:v1
    restart: always
    networks:
      - inception-network

  adminer:
    build: ./requirements/bonus/adminer
    container_name: inception-adminer
    image: adminer:v1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception-network

  website:
    build: ./requirements/bonus/website
    container_name: inception-website
    image: website:v1
    restart: always
    ports:
      - "90:90"
    networks:
      - inception-network
    env_file:
      - .env

  ftp:
    build: ./requirements/bonus/ftp
    container_name: inception-ftp
    image: ftp:v1
    restart: always
    ports:
      - "210:21"
      - "21000-21010:21000-21010"
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env

  portainer:
    build: ./requirements/bonus/portainer
    container_name: inception-portainer
    image: portainer:v1
    restart: always
    ports:
      - "9000:9000"
    networks:
      - inception-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

# for volumes that are bound to a host directory:make sure the volume path exists
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  portainer_data:
    name: portainer_data
    driver: local

networks:
  inception-network:
    name: inception-network
    driver: bridge